shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - '@yarnpkg/libzip@3.2.2'

allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  dtrace-provider: true
  esbuild: true
  protobufjs: true
  re2: true
  simple-git-hooks: true
