name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Required permission: github repo => settings => actions => Allow GitHub Actions to create and approve pull requests
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  # publish:
  #   needs: release
  #   if: ${{ needs.release.outputs.release_created }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v6
  #       with:
  #         run_install: false

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 24.16.0
  #         registry-url: 'https://registry.npmjs.org'
  #         cache: pnpm

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Publish to NPM
  #       run: npm publish
